apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fashion-trends

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - qdrant.yaml
  - api-gateway.yaml
  - image-processor.yaml
  - ml-analysis.yaml

commonLabels:
  app.kubernetes.io/part-of: fashion-trend-analysis
  app.kubernetes.io/managed-by: kustomize
